# Generated by Django 4.2.1 on 2023-06-07 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcitymodel',
            name='subcity_address',
            field=models.CharField(default='It is located in the center of Addis Ababa city, next to the Cancer treatment center', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcitymodel',
            name='subcity_email',
            field=models.ImageField(blank=True, max_length=255, upload_to=''),
        ),
        migrations.AddField(
            model_name='subcitymodel',
            name='subcity_phone_number',
            field=models.CharField(default='+251910609442', max_length=20),
            preserve_default=False,
        ),
    ]
