# Generated by Django 4.2.1 on 2023-06-07 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_subcitymodel_subcity_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcitymodel',
            name='subcity_email',
            field=models.EmailField(blank=True, max_length=255),
        ),
    ]
