# Generated by Django 4.2.1 on 2023-06-07 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_subcitymodel_subcity_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcitymodel',
            name='youtube_link',
            field=models.URLField(blank=True),
        ),
    ]
