# Generated by Django 4.2.1 on 2023-06-07 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_subcitymodel_youtube_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcitymodel',
            name='address',
        ),
        migrations.RemoveField(
            model_name='subcitymodel',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='subcitymodel',
            name='carousel_title',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='subcitymodel',
            name='subcity_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='subcitymodel',
            name='subcity_phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
