# Generated by Django 4.2.1 on 2023-06-07 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_subcitymodel_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcitymodel',
            name='logo',
            field=models.ImageField(default='logo', upload_to='media/logo/'),
            preserve_default=False,
        ),
    ]
