# Generated by Django 4.2.1 on 2023-06-07 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_headlinenewsmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsmodel',
            old_name='new_title',
            new_name='news_title',
        ),
        migrations.RemoveField(
            model_name='newsmodel',
            name='headline_news_body',
        ),
        migrations.RemoveField(
            model_name='newsmodel',
            name='headline_news_image',
        ),
        migrations.RemoveField(
            model_name='newsmodel',
            name='headline_news_title',
        ),
    ]
