# Generated by Django 4.2.1 on 2023-06-07 14:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_rename_new_title_newsmodel_news_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallerymodel',
            options={'ordering': ('-date_created',)},
        ),
        migrations.AddField(
            model_name='gallerymodel',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
