# Generated by Django 4.2.1 on 2023-06-08 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_gallerymodel_gallery_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinetmodel',
            name='cabinate_message',
            field=models.TextField(default='message from cabinates'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cabinetmodel',
            name='work_experience',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
