# Generated by Django 4.2.1 on 2023-06-08 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_cabinetmodel_cabinate_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcitymodel',
            name='chief_executive_image',
        ),
        migrations.RemoveField(
            model_name='subcitymodel',
            name='chief_executive_message',
        ),
        migrations.RemoveField(
            model_name='subcitymodel',
            name='chief_executive_name',
        ),
        migrations.AddField(
            model_name='woredamodel',
            name='woreda_image',
            field=models.ImageField(default='woreda 1', upload_to='media/woredas'),
            preserve_default=False,
        ),
    ]
