# Generated by Django 4.2.1 on 2023-06-08 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_subcitymodel_chief_executive_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcitymodel',
            name='area_of_subcity',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='subcitymodel',
            name='elivation',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='subcitymodel',
            name='logo',
            field=models.ImageField(blank=True, upload_to='media/logo/'),
        ),
        migrations.AlterField(
            model_name='subcitymodel',
            name='population',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='tendermodel',
            name='date_created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='tendermodel',
            name='expired_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='vacancymodel',
            name='date_created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='vacancymodel',
            name='expired_date',
            field=models.DateTimeField(),
        ),
    ]
