# Generated by Django 4.2.1 on 2023-06-08 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_subcitymodel_area_of_subcity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcitymodel',
            name='area_of_subcity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='subcitymodel',
            name='elivation',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='subcitymodel',
            name='population',
            field=models.IntegerField(null=True),
        ),
    ]
