# Generated by Django 4.2.1 on 2023-06-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_subcitymodel_area_of_subcity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carousel_image', models.ImageField(upload_to='media/carousels/')),
                ('carousel_title', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='subcitymodel',
            name='carousel_image',
        ),
        migrations.RemoveField(
            model_name='subcitymodel',
            name='carousel_title',
        ),
        migrations.AlterField(
            model_name='subcitymodel',
            name='area_of_subcity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subcitymodel',
            name='elivation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subcitymodel',
            name='population',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
